### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by lisonge** [lckr/jupyterlab-variableInspector#129]
# win10x64 npm@6.13.4 node@v12.14.1
## error log
```powershell
⨯ 19055 ~ ❯❯❯ cd E:/Documents/git/jupyterlab-variableInspector
19055 E:\..\..\jupyterlab-variableInspector git: master ≣ ❯❯❯ npm run build

> @lckr/jupyterlab_variableinspector@0.4.0 build E:\Documents\git\jupyterlab-variableInspector      
> tsc

src/handler.ts:18:5 - error TS2305: Module '"../../../../Documents/git/jupyterlab-variableInspector/node_modules/_@jupyterlab_apputils@2.0.2@@jupyterlab/apputils/lib"' has no exported member 'IClientSession'.

18     IClientSession
       ~~~~~~~~~~~~~~

src/handler.ts:30:5 - error TS2305: Module '"../../../../Documents/git/jupyterlab-variableInspector/node_modules/_@jupyterlab_coreutils@4.0.2@@jupyterlab/coreutils/lib"' has no exported member 'nbformat'.

30     nbformat
       ~~~~~~~~

src/index.ts:50:9 - error TS2322: Type 'import("E:/Documents/git/jupyterlab-variableInspector/node_modules/_@phosphor_coreutils@1.3.1@@phosphor/coreutils/lib/token").Token<import("E:/Documents/git/jupyterlab-variableInspector/src/manager").IVariableInspectorManager>' is not assignable to type 'import("E:/Documents/git/jupyterlab-variableInspector/node_modules/_@lumino_coreutils@1.4.2@@lumino/coreutils/lib/token").Token<import("E:/Documents/git/jupyterlab-variableInspector/src/manager").IVariableInspectorManager>'.
  Types have separate declarations of a private property '_tokenStructuralPropertyT'.

50         provides: IVariableInspectorManager,
           ~~~~~~~~

  node_modules/_@lumino_application@1.8.4@@lumino/application/lib/index.d.ts:66:5
    66     provides?: Token<U>;
           ~~~~~~~~
    The expected type comes from property 'provides' which is declared here on type 'JupyterFrontEndPlugin<IVariableInspectorManager>'

src/index.ts:60:47 - error TS2344: Type 'VariableInspectorPanel' does not satisfy the constraint 'Widget'.
  Types of property 'title' are incompatible.
    Type 'import("E:/Documents/git/jupyterlab-variableInspector/node_modules/_@phosphor_widgets@1.9.3@@phosphor/widgets/lib/title").Title<import("E:/Documents/git/jupyterlab-variableInspector/node_modules/_@phosphor_widgets@1.9.3@@phosphor/widgets/lib/widget").Widget>' is not assignable to type 'import("E:/Documents/git/jupyterlab-variableInspector/node_modules/_@lumino_widgets@1.11.1@@lumino/widgets/lib/title").Title<import("E:/Documents/git/jupyterlab-variableInspector/node_modules/_@lumino_widgets@1.11.1@@lumino/widgets/lib/widget").Widget>'.

60             const tracker = new WidgetTracker<VariableInspectorPanel>( { namespace } );
                                                 ~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:99:39 - error TS2345: Argument of type 'VariableInspectorPanel' is not assignable to parameter of type 'Widget'.
  Types of property 'title' are incompatible.
    Type 'import("E:/Documents/git/jupyterlab-variableInspector/node_modules/_@phosphor_widgets@1.9.3@@phosphor/widgets/lib/title").Title<import("E:/Documents/git/jupyterlab-variableInspector/node_modules/_@phosphor_widgets@1.9.3@@phosphor/widgets/lib/widget").Widget>' is not assignable to type 'import("E:/Documents/git/jupyterlab-variableInspector/node_modules/_@lumino_widgets@1.11.1@@lumino/widgets/lib/title").Title<import("E:/Documents/git/jupyterlab-variableInspector/node_modules/_@lumino_widgets@1.11.1@@lumino/widgets/lib/widget").Widget>'.

99                         labShell.add( manager.panel, 'main' );
                                         ~~~~~~~~~~~~~

src/index.ts:117:20 - error TS2322: Type 'Token<IVariableInspectorManager>' is not assignable to type 'Token<any>'.
  Types have separate declarations of a private property '_tokenStructuralPropertyT'.

117         requires: [IVariableInspectorManager, IConsoleTracker, ILabShell],
                       ~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:127:53 - error TS2339: Property 'session' does not exist on type 'ConsolePanel'.       
127                 if (manager.hasHandler(consolePanel.session.path)){
                                                        ~~~~~~~

src/index.ts:129:65 - error TS2339: Property 'session' does not exist on type 'ConsolePanel'.       
129                         resolve(manager.getHandler(consolePanel.session.path));
                                                                    ~~~~~~~

src/index.ts:133:54 - error TS2339: Property 'session' does not exist on type 'ConsolePanel'.       
133                         const session = consolePanel.session;
                                                         ~~~~~~~

src/index.ts:221:20 - error TS2322: Type 'Token<IVariableInspectorManager>' is not assignable to type 'Token<any>'.

221         requires: [IVariableInspectorManager, INotebookTracker, ILabShell],
                       ~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:235:45 - error TS2339: Property 'session' does not exist on type 'NotebookPanel'.

235                     const session = nbPanel.session;
                                                ~~~~~~~

src/kernelconnector.ts:2:5 - error TS2305: Module '"../../../../Documents/git/jupyterlab-variableInspector/node_modules/_@jupyterlab_apputils@2.0.2@@jupyterlab/apputils/lib"' has no exported member 'IClientSession'.

2     IClientSession
      ~~~~~~~~~~~~~~

src/kernelconnector.ts:25:47 - error TS7006: Parameter 'sender' implicitly has an 'any' type.       
25         this._session.statusChanged.connect( (sender, new_status: Kernel.Status) =>{
                                                 ~~~~~~

src/variableinspector.ts:216:31 - error TS2345: Argument of type 'SimplifiedOutputArea' is not assignable to parameter of type 'Widget'.
  The types of 'title.owner.layout.removeWidget' are incompatible between these types.
    Type '(widget: import("E:/Documents/git/jupyterlab-variableInspector/node_modules/_@lumino_widgets@1.11.1@@lumino/widgets/lib/widget").Widget) => void' is not assignable to type '(widget: import("E:/Documents/git/jupyterlab-variableInspector/node_modules/_@phosphor_widgets@1.9.3@@phosphor/widgets/lib/widget").Widget) => void'.
      Types of parameters 'widget' and 'widget' are incompatible.
        Type 'import("E:/Documents/git/jupyterlab-variableInspector/node_modules/_@phosphor_widgets@1.9.3@@phosphor/widgets/lib/widget").Widget' is not assignable to type 'import("E:/Documents/git/jupyterlab-variableInspector/node_modules/_@lumino_widgets@1.11.1@@lumino/widgets/lib/widget").Widget'.          Types of property 'title' are incompatible.
            Type 'Title<Widget>' is missing the following properties from type 'Title<Widget>': iconRenderer, _icon

216                 Widget.attach(output, cell);
                                  ~~~~~~


Found 14 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @lckr/jupyterlab_variableinspector@0.4.0 build: `tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @lckr/jupyterlab_variableinspector@0.4.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.  
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\19055\AppData\Roaming\npm-cache\_logs\2020-03-06T18_43_23_461Z-debug.log      
19055 E:\..\..\jupyterlab-variableInspector git: master ≣ ❯❯❯
```
## log file 2020-03-06T18_43_23_461Z-debug.log
```log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @lckr/jupyterlab_variableinspector@0.4.0~prebuild: @lckr/jupyterlab_variableinspector@0.4.0
6 info lifecycle @lckr/jupyterlab_variableinspector@0.4.0~build: @lckr/jupyterlab_variableinspector@0.4.0
7 verbose lifecycle @lckr/jupyterlab_variableinspector@0.4.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle @lckr/jupyterlab_variableinspector@0.4.0~build: PATH: D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Documents\git\jupyterlab-variableInspector\node_modules\.bin;D:\Program Files\Python\Python37\Scripts\;D:\Program Files\Python\Python37\;D:\Program Files\ImageMagick-7.0.9-Q16;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\Program Files\java\jdk1.8.0_212\bin;D:\Program Files\gradle\gradle-6.1.1\bin;D:\Program Files (x86)\Lua\5.1;D:\Program Files (x86)\Lua\5.1\clibs;D:\Android\SDK\platform-tools;D:\Program Files\xampp\php;D:\Program Files\xampp\php\ext;D:\Program Files\texlive\2019\bin\win32;D:\Program Files\Strawberry\c\bin;D:\Program Files\Strawberry\perl\site\bin;D:\Program Files\Strawberry\perl\bin;D:\Program Files (x86)\Graphviz2.38\bin;C:\ProgramData\chocolatey\bin;D:\Program Files\Git\cmd;D:\Program Files\nodejs\;D:\Program Files\PowerShell\6\;C:\Program Files\dotnet\;C:\Users\19055\.windows-build-tools\python27\;C:\Users\19055\scoop\shims;C:\Users\19055\AppData\Local\Microsoft\WindowsApps;C:\Users\19055\AppData\Local\hyper\app-3.0.2\resources\bin;C:\Users\19055\AppData\Local\Programs\Microsoft VS Code\bin;D:\Program Files\Microsoft VS Code\bin;C:\Users\19055\AppData\Local\Programs\Fiddler;D:\Program Files\Fiddler;C:\Users\19055\AppData\Local\GitHubDesktop\bin;D:\Program Files\Bandizip\;C:\Users\19055\AppData\Roaming\npm;D:\Program Files (x86)\GitHub CLI\;C:\Users\19055\.dotnet\tools
9 verbose lifecycle @lckr/jupyterlab_variableinspector@0.4.0~build: CWD: E:\Documents\git\jupyterlab-variableInspector
10 silly lifecycle @lckr/jupyterlab_variableinspector@0.4.0~build: Args: [ '/d /s /c', 'tsc' ]
11 silly lifecycle @lckr/jupyterlab_variableinspector@0.4.0~build: Returned: code: 1  signal: null
12 info lifecycle @lckr/jupyterlab_variableinspector@0.4.0~build: Failed to exec build script
13 verbose stack Error: @lckr/jupyterlab_variableinspector@0.4.0 build: `tsc`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:223:5)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:223:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid @lckr/jupyterlab_variableinspector@0.4.0
15 verbose cwd E:\Documents\git\jupyterlab-variableInspector
16 verbose Windows_NT 10.0.18363
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.14.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error @lckr/jupyterlab_variableinspector@0.4.0 build: `tsc`
22 error Exit status 1
23 error Failed at the @lckr/jupyterlab_variableinspector@0.4.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by lckr** [comment]
Hey, are you using jupyterlab 2.0  by any chance? 
There are some breaking changes introduced with the new jupyterlab version. This extension is not yet updated to work with jlab 2.0, but I'm working on it.

**Comment by lisonge** [comment]
yes, my jupyterlab is 2.0.0, but i just only run
```powershell
npm run build
```
does npm-build have anything to do with jupyterlab?

```powershell
19055 ~ ❯❯❯ pip list
Package                           Version
--------------------------------- ----------
adbutils                          0.7.1
apkutils2                         1.0.0
arrow                             0.15.5
astroid                           2.3.3
attrs                             19.3.0
autopep8                          1.4.4
backcall                          0.1.0
beautifulsoup4                    4.8.2
bleach                            3.1.1
certifi                           2019.11.28
cffi                              1.13.2
chardet                           3.0.4
cigam                             0.0.3
colorama                          0.4.1
decorator                         4.4.1
defusedxml                        0.6.0
Deprecated                        1.2.7
deprecation                       2.0.7
entrypoints                       0.3
facebook-wda                      0.4.2
gevent                            1.4.0
greenlet                          0.4.15
h11                               0.9.0
h2                                3.2.0
hpack                             3.0.0
hstspreload                       2020.3.4
html5lib                          1.0.1
httpx                             0.11.1
humanize                          0.5.1
hyperframe                        5.2.0
idna                              2.8
importlib-metadata                1.5.0
ipykernel                         5.1.4
ipython                           7.13.0
ipython-genutils                  0.2.0
iso8601                           0.1.12
isort                             4.3.21
jedi                              0.16.0
Jinja2                            2.11.1
json5                             0.9.2
jsonschema                        3.2.0
jupyter-client                    6.0.0
jupyter-contrib-core              0.3.3
jupyter-core                      4.6.3
jupyter-highlight-selected-word   0.2.0
jupyter-latex-envs                1.4.6
jupyter-nbextensions-configurator 0.4.1
jupyterlab                        2.0.0
jupyterlab-server                 1.0.7
lazy-object-proxy                 1.4.3
leancloud                         2.5.0
logzero                           1.5.0
lxml                              4.5.0
MarkupSafe                        1.1.1
mccabe                            0.6.1
mistune                           0.8.4
mpmath                            1.1.0
nbconvert                         5.6.1
nbformat                          5.0.4
nltk                              3.4.5
notebook                          6.0.3
numpy                             1.18.1
opencv-python                     4.2.0.32
packaging                         20.1
pandas                            1.0.1
pandocfilters                     1.4.2
parso                             0.6.2
pickleshare                       0.7.5
Pillow                            7.0.0
pip                               19.3.1
progress                          1.5
prometheus-client                 0.7.1
prompt-toolkit                    3.0.3
py                                1.8.1
pycodestyle                       2.5.0
pycparser                         2.19
pyelftools                        0.26
Pygments                          2.5.2
pylint                            2.4.4
pyparsing                         2.4.6
pypinyin                          0.37.0
pyrsistent                        0.15.7
python-dateutil                   2.8.1
pytz                              2019.3
pywin32                           227
pywinpty                          0.5.7
PyYAML                            5.3
pyzmq                             19.0.0
qiniu                             7.2.2
requests                          2.22.0
retry                             0.9.2
rfc3986                           1.3.2
rope                              0.14.0
Send2Trash                        1.5.0
setuptools                        40.8.0
six                               1.14.0
sniffio                           1.1.0
soupsieve                         2.0
sympy                             1.5.1
terminado                         0.8.3
testpath                          0.4.4
tornado                           6.0.3
traitlets                         4.3.3
typed-ast                         1.4.0
uiautomator2                      2.5.3
urllib3                           1.25.3
wcwidth                           0.1.8
webencodings                      0.5.1
weditor                           0.4.2
Werkzeug                          0.16.1
whichcraft                        0.6.1
wrapt                             1.11.2
xmltodict                         0.12.0
zipp                              3.1.0
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by wtzeng1** [comment]
@lisonge I meet the same problem, and find that it caused by the loose version specification in the package.json, just using more stricter version specification then everything is fine.

package.json:

```json
{
  "dependencies": {
    "@jupyterlab/application": "^1.0.0",
    "@jupyterlab/apputils": "^1.0.0",
    "@jupyterlab/console": "^1.0.0",
    "@jupyterlab/coreutils": "^3.0.0",
    "@jupyterlab/csvviewer": "^1.0.0",
    "@jupyterlab/notebook": "^1.0.0",
    "@jupyterlab/services": "^4.0.0",
    "@phosphor/datagrid": "~0.1.9"
  }
}
```

reference: https://docs.npmjs.com/files/package.json#dependencies
