### ISSUE TITLE
Cannot work on Jupyterlab 2.0?

### ISSUE THREAD

**Issue by MrUkulele** [lckr/jupyterlab-variableInspector#134]
After installing this extension, i found that it cannot work. 
JupyterLab failed to build

**Comment by lckr** [comment]
Hey, can you give me some more information about the build failure? Are you building JupyterLab from source? Are you installing the extension manually or with the extension manager?

**Comment by zimka** [comment]
Also faced error installing extension for jupyterlab 2(Ubuntu 18.04 LTS, python 3.7) by `jupyter labextension install @lckr/jupyterlab_variableinspector` :
> Building jupyterlab assets (build:prod:minimize)
> The extension "jupyterlab_discovery" is outdated.
> 
> An error occured.
> RuntimeError: npm dependencies failed to install
> See the log file for details:  /tmp/jupyterlab-debug-74u8v80h.log
> 

Log and pip packages  are attached
[varinspector_pip_freeze.log](https://github.com/lckr/jupyterlab-variableInspector/files/4387437/varinspector_pip_freeze.log)
are attached
[varinspector_error.log](https://github.com/lckr/jupyterlab-variableInspector/files/4387436/varinspector_error.log)

**Comment by MrUkulele** [comment]
after installing extension for jupyterlab 2 on MacOS 10.14.1  by cloning the repository with git clone https://github.com/lckr/jupyterlab-variableInspector,the following steps have some problems:

- Unexpected end of JSON input while parsing near '...5e8cd21413c191d496fcb'
- npm ERR! A complete log of this run can be found in:
- npm ERR!     /Users/aaron/.npm/_logs/2020-03-26T16_52_08_487Z-debug.log
m ERR! code ELIFECYCLE

- npm ERR! syscall spawn
- npm ERR! file sh
- npm ERR! errno ENOENT
- npm ERR! @lckr/jupyterlab_variableinspector@0.4.0 build: `tsc`
- npm ERR! spawn ENOENT
- npm ERR! 
- npm ERR! Failed at the @lckr/jupyterlab_variableinspector@0.4.0 build script.
- npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

- An error occured.
- RuntimeError: JupyterLab failed to build

**Comment by lckr** [comment]
Hey, it seems like the extension somehow cannot be found during the build process of jupyterlab.
`Error: Cannot find module '@lckr/jupyterlab_variableinspector/package.json'

If I understand you right, you cloned this repo from github and are trying to install the extension with the following steps:
```
cd jupyterlab-variableInspector
npm install
npm run build
jupyter labextension install .
```
Can you tell me at which of these the error occurred?

**Comment by MrUkulele** [comment]
I have tried to reinstall this extension, but there is always the same error 'RuntimeError: JupyterLab failed to build' after i tried 'jupyter labextension install '

**Comment by lckr** [comment]
Maybe a dumb question, but did you run it with the dot at the end of the command?:
```
jupyter labextension install .
```

**Comment by MrUkulele** [comment]
nope. i just run it by 'jupyter labextension install'

**Comment by lckr** [comment]
Can you try it again with the dot at the end?

**Comment by MrUkulele** [comment]
still the same error with the dot at the end :(

**Comment by finlu** [comment]
> Can you try it again with the dot at the end?

I try the same command, but found errors as follow:
> node /home/adv/.apps/anaconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:dev:minimize
yarn run v1.21.1
$ jlpm run build:dev
$ jlpm run build
$ webpack
/home/adv/.apps/anaconda3/share/jupyter/lab/staging/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

Error: Cannot find module '@lckr/jupyterlab_variableinspector/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.resolve (/home/adv/.apps/anaconda3/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:166:23)
    at /home/adv/.apps/anaconda3/share/jupyter/lab/staging/webpack.config.js:59:32
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/adv/.apps/anaconda3/share/jupyter/lab/staging/webpack.config.js:57:34)
    at Module._compile (/home/adv/.apps/anaconda3/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (/home/adv/.apps/anaconda3/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/home/adv/.apps/anaconda3/share/jupyter/lab/staging/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/home/adv/.apps/anaconda3/share/jupyter/lab/staging/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /home/adv/.apps/anaconda3/share/jupyter/lab/staging/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/adv/.apps/anaconda3/share/jupyter/lab/staging/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at yargs.parse (/home/adv/.apps/anaconda3/share/jupyter/lab/staging/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/home/adv/.apps/anaconda3/share/jupyter/lab/staging/node_modules/yargs/yargs.js:567:18)
    at /home/adv/.apps/anaconda3/share/jupyter/lab/staging/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/adv/.apps/anaconda3/share/jupyter/lab/staging/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/adv/.apps/anaconda3/share/jupyter/lab/staging/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
error Command failed with exit code 1.

I think it might caused by the version of webpack?

**Comment by berdakh** [comment]
I have the same problem. The variable inspector does not work with version 2. 
I would appreciate it if this problem could be solved, somehow.

**Comment by MrUkulele** [comment]
i have solved this problem by reference https://github.com/lckr/jupyterlab-variableInspector/issues/143#issuecomment-620213380.
