### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by reyhanhgh** [lckr/jupyterlab-variableInspector#192]
I am new to jupyterlab. I tried to install the variable inspector following the given instructions, but I did not manage. Here is what `pip install -e .` outputs me:
```
Obtaining file:///home/myname/PycharmProjects/pythonProject/jupyterlab-variableInspector
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing wheel metadata ... done
Requirement already satisfied: jupyterlab==3.*,>=3.0.0rc13 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from lckr-jupyterlab-variableinspector===3.0.) (3.0.6)
Requirement already satisfied: jupyter-server~=1.2 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (1.2.2)
Requirement already satisfied: ipython in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (7.20.0)
Requirement already satisfied: packaging in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (20.9)
Requirement already satisfied: nbclassic~=0.2 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.2.6)
Requirement already satisfied: jinja2>=2.10 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (2.11.3)
Requirement already satisfied: jupyter-core in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (4.7.1)
Requirement already satisfied: jupyterlab-server~=2.0 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (2.1.3)
Requirement already satisfied: tornado>=6.1.0 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (6.1)
Requirement already satisfied: MarkupSafe>=0.23 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jinja2>=2.10->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (1.1.1)
Requirement already satisfied: jupyter-client>=6.1.1 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (6.1.11)
Requirement already satisfied: nbformat in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (5.1.2)
Requirement already satisfied: Send2Trash in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (1.5.0)
Requirement already satisfied: prometheus-client in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.9.0)
Requirement already satisfied: terminado>=0.8.3 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.9.2)
Requirement already satisfied: pyzmq>=17 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (22.0.2)
Requirement already satisfied: ipython-genutils in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.2.0)
Requirement already satisfied: nbconvert in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (6.0.7)
Requirement already satisfied: anyio>=2.0.2 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (2.0.2)
Requirement already satisfied: traitlets>=4.2.1 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (5.0.5)
Requirement already satisfied: idna>=2.8 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from anyio>=2.0.2->jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (2.10)
Requirement already satisfied: sniffio>=1.1 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from anyio>=2.0.2->jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (1.2.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyter-client>=6.1.1->jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (2.8.1)
Requirement already satisfied: json5 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyterlab-server~=2.0->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.9.5)
Requirement already satisfied: requests in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyterlab-server~=2.0->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (2.25.1)
Requirement already satisfied: babel in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyterlab-server~=2.0->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (2.9.0)
Requirement already satisfied: jsonschema>=3.0.1 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jupyterlab-server~=2.0->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (3.2.0)
Requirement already satisfied: six>=1.11.0 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.0->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (1.15.0)
Requirement already satisfied: setuptools in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.0->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (53.0.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.0->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.0->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (20.3.0)
Requirement already satisfied: notebook<7 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from nbclassic~=0.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (6.2.0)
Requirement already satisfied: ipykernel in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from notebook<7->nbclassic~=0.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (5.4.3)
Requirement already satisfied: argon2-cffi in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from notebook<7->nbclassic~=0.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (20.1.0)
Requirement already satisfied: ptyprocess in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from terminado>=0.8.3->jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.7.0)
Requirement already satisfied: cffi>=1.0.0 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from argon2-cffi->notebook<7->nbclassic~=0.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (1.14.4)
Requirement already satisfied: pycparser in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from cffi>=1.0.0->argon2-cffi->notebook<7->nbclassic~=0.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (2.20)
Requirement already satisfied: pytz>=2015.7 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from babel->jupyterlab-server~=2.0->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (2021.1)
Requirement already satisfied: decorator in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (4.4.2)
Requirement already satisfied: pickleshare in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.7.5)
Requirement already satisfied: pygments in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (2.7.4)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (3.0.14)
Requirement already satisfied: jedi>=0.16 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.18.0)
Requirement already satisfied: backcall in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (4.8.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from jedi>=0.16->ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.8.1)
Requirement already satisfied: wcwidth in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.2.5)
Requirement already satisfied: entrypoints>=0.2.2 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from nbconvert->jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.3)
Requirement already satisfied: pandocfilters>=1.4.1 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from nbconvert->jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (1.4.3)
Requirement already satisfied: defusedxml in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from nbconvert->jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.6.0)
Requirement already satisfied: testpath in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from nbconvert->jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.4.4)
Requirement already satisfied: jupyterlab-pygments in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from nbconvert->jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.1.2)
Requirement already satisfied: mistune<2,>=0.8.1 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from nbconvert->jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.8.4)
Requirement already satisfied: bleach in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from nbconvert->jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (3.3.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from nbconvert->jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.5.1)
Requirement already satisfied: async-generator in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (1.10)
Requirement already satisfied: nest-asyncio in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (1.5.1)
Requirement already satisfied: webencodings in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from bleach->nbconvert->jupyter-server~=1.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (0.5.1)
Requirement already satisfied: pyparsing>=2.0.2 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from packaging->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (2.4.7)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from requests->jupyterlab-server~=2.0->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from requests->jupyterlab-server~=2.0->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (1.26.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages (from requests->jupyterlab-server~=2.0->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector===3.0.) (2020.12.5)
Installing collected packages: lckr-jupyterlab-variableinspector
Attempting uninstall: lckr-jupyterlab-variableinspector
Found existing installation: lckr-jupyterlab-variableinspector 3.0.6
Uninstalling lckr-jupyterlab-variableinspector-3.0.6:
  Successfully uninstalled lckr-jupyterlab-variableinspector-3.0.6
Running setup.py develop for lckr-jupyterlab-variableinspector
ERROR: Command errored out with exit status 1:
  command: /home/myname/PycharmProjects/pythonProject/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/myname/PycharmProjects/pythonProject/jupyterlab-variableInspector/setup.py'"'"'; __file__='"'"'/home/myname/PycharmProjects/pythonProject/jupyterlab-variableInspector/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
cwd: /home/myname/PycharmProjects/pythonProject/jupyterlab-variableInspector/
  Complete output (42 lines):
  running develop
running jsdeps
Installing build dependencies with npm.  This may take a while...
> jlpm install
yarn install v1.21.1
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
error marked@1.2.7: The engine "node" is incompatible with this module. Expected version ">= 8.16.2". Got "8.10.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
/tmp/pip-build-env-ee4ytvcp/overlay/lib/python3.8/site-packages/setuptools/dist.py:475: UserWarning: The version specified ('3.0.') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
warnings.warn(
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/myname/PycharmProjects/pythonProject/jupyterlab-variableInspector/setup.py", line 93, in <module>
    setuptools.setup(**setup_args)
  File "/tmp/pip-build-env-ee4ytvcp/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
  return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
  dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
  self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
  cmd_obj.run()
  File "/tmp/pip-build-env-ee4ytvcp/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 503, in run
  [self.run_command(cmd) for cmd in cmds]
  File "/tmp/pip-build-env-ee4ytvcp/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 503, in <listcomp>
    [self.run_command(cmd) for cmd in cmds]
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
  self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
  cmd_obj.run()
  File "/tmp/pip-build-env-ee4ytvcp/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 274, in run
  c.run()
  File "/tmp/pip-build-env-ee4ytvcp/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 379, in run
  run(npm_cmd + ['install'], cwd=node_package)
  File "/tmp/pip-build-env-ee4ytvcp/overlay/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 225, in run
  return subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
  raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/tmp/pip-build-env-ee4ytvcp/overlay/bin/jlpm', 'install']' returned non-zero exit status 1.
  ----------------------------------------
    Rolling back uninstall of lckr-jupyterlab-variableinspector
  Moving to /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/lckr_jupyterlab_variableinspector-3.0.6.dist-info/
    from /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/~ckr_jupyterlab_variableinspector-3.0.6.dist-info
  Moving to /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/lckr_jupyterlab_variableinspector/
    from /home/myname/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/~ckr_jupyterlab_variableinspector
  Moving to /home/myname/PycharmProjects/pythonProject/venv/share/jupyter/labextension
```
 What am I doing wrong? Thanks

**Comment by lckr** [comment]
Check your output: `The engine "node" is incompatible with this module. Expected version ">= 8.16.2". Got "8.10.0"`

**Comment by reyhanhgh** [comment]
@lckr  No this appears only when I use this loss function!!! Using "mse" as loss function, I don't get any errors!
