### ISSUE TITLE
Win 10 npm install: can't jupyter lab build the inspector

### ISSUE THREAD

**Issue by brettbrocato** [lckr/jupyterlab-variableInspector#74]
please note: though I am on Windows 10, "B:" drive is not a floppy : )

I got npm install to run behind my corporate proxy.  My _variableinspector reports "enabled  ok*", but it's recommended that I run 'jupyter lab build'.  After I did, I still have the same state.  The Jupyter Lab UI also shows a dialog that I need to run jupyter lab build.  Do I somehow need to explicitly include the inspector?

I just yarn-error2.log, very lightly scrubbed for my corporate id#. I tried this a second time after noticing the Docker and Anaconda paths, which are not where I'm trying to install extensions. I had the failure above, uninstalled Docker, deleted Docker paths in Windows Ctrl Panel, deleted Anaconda paths in Windows Ctrl Panel, and got all the same errors as far as I could tell. I'm not sure where the Docker and Anaconda information are still coming from in yarn-error.log .

I have now npm installed 'webpack', 'webpack-cli', and 'fs-extra'

`B:\WPy-3670q\scripts\jupyterlab-variableInspector>jupyter lab build
[LabBuildApp] JupyterLab 0.35.3
[LabBuildApp] Cleaning B:\WPy-3670q\python-3.6.7.amd64\share\jupyter\lab
Cleaning B:\WPy-3670q\python-3.6.7.amd64\share\jupyter\lab...
Success!
[LabBuildApp] Building in B:\WPy-3670q\python-3.6.7.amd64\share\jupyter\lab
[LabBuildApp] Node v8.12.0

[LabBuildApp] > B:\WPy-3670q\python-3.6.7.amd64\..\t\n\npm.CMD pack B:\WPy-3670q\scripts\jupyterlab-variableInspector

> jupyterlab_variableinspector@0.1.0 prepare B:/WPy-3670q/scripts/jupyterlab-variableInspector
> npm run clean && npm run build

> jupyterlab_variableinspector@0.1.0 clean B:\WPy-3670q\scripts\jupyterlab-variableInspector
> rimraf lib

> jupyterlab_variableinspector@0.1.0 build B:\WPy-3670q\scripts\jupyterlab-variableInspector
> tsc

npm notice
npm notice package: jupyterlab_variableinspector@0.1.0
npm notice === Tarball Contents ===
npm notice 1.4kB  package.json
npm notice 1.1kB  LICENSE
npm notice 2.0kB  README.md
npm notice 2.7kB  lib/handler.d.ts
npm notice 10.3kB lib/handler.js
npm notice 180B   lib/index.d.ts
npm notice 10.5kB lib/index.js
npm notice 507B   lib/inspectorscripts.d.ts
npm notice 8.9kB  lib/inspectorscripts.js
npm notice 1.4kB  lib/kernelconnector.d.ts
npm notice 3.4kB  lib/kernelconnector.js
npm notice 1.2kB  lib/manager.d.ts
npm notice 2.8kB  lib/manager.js
npm notice 1.9kB  lib/variableinspector.d.ts
npm notice 6.5kB  lib/variableinspector.js
npm notice 1.0kB  style/index.css
npm notice === Tarball Details ===
npm notice name:          jupyterlab_variableinspector
npm notice version:       0.1.0
npm notice filename:      jupyterlab_variableinspector-0.1.0.tgz
npm notice package size:  12.4 kB
npm notice unpacked size: 55.8 kB
npm notice shasum:        93344a5a23ef583ca7cdf76286bc0626dca9fa4d
npm notice integrity:     sha512-vgmvZAnuTP7ER[...]UfAdPa1EjrSgw==
npm notice total files:   16
npm notice
jupyterlab_variableinspector-0.1.0.tgz
[LabBuildApp] > node B:\WPy-3670q\python-3.6.7.amd64\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.9.4
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@jupyterlab%2fapplication: unable to get local issuer certificate".
info If you think this is a bug, please open a bug report with the information provided in "B:\\WPy-3670q\\python-3.6.7.amd64\\share\\jupyter\\lab\\staging\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[LabBuildApp] > node B:\WPy-3670q\python-3.6.7.amd64\lib\site-packages\jupyterlab\staging\yarn.js run build
yarn run v1.9.4
$ webpack
B:\WPy-3670q\t\n\node_modules\webpack-cli\bin\cli.js:235
                                throw err;
                                ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (B:\WPy-3670q\t\n\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (B:\WPy-3670q\python-3.6.7.amd64\share\jupyter\lab\staging\webpack.config.js:7:10)
    at Module._compile (B:\WPy-3670q\t\n\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (B:\WPy-3670q\t\n\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (B:\WPy-3670q\t\n\node_modules\webpack-cli\bin\convert-argv.js:115:13)
    at requireConfig (B:\WPy-3670q\t\n\node_modules\webpack-cli\bin\convert-argv.js:117:6)
    at B:\WPy-3670q\t\n\node_modules\webpack-cli\bin\convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (B:\WPy-3670q\t\n\node_modules\webpack-cli\bin\convert-argv.js:122:15)
    at yargs.parse (B:\WPy-3670q\t\n\node_modules\webpack-cli\bin\cli.js:232:39)
    at Object.parse (B:\WPy-3670q\t\n\node_modules\webpack-cli\node_modules\yargs\yargs.js:567:18)
    at B:\WPy-3670q\t\n\node_modules\webpack-cli\bin\cli.js:210:8
    at Object.<anonymous> (B:\WPy-3670q\t\n\node_modules\webpack-cli\bin\cli.js:500:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (B:\WPy-3670q\t\n\node_modules\webpack\bin\webpack.js:155:2)
    at Module._compile (module.js:653:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
[yarn-error.log](https://github.com/lckr/jupyterlab-variableInspector/files/2774218/yarn-error.log)
[yarn-error2.log](https://github.com/lckr/jupyterlab-variableInspector/files/2774303/yarn-error2.log)

**Comment by brettbrocato** [comment]
I just uploaded yarn-error.log, very lightly scrubbed for my corporate id#.  I tried this a second time after noticing the Docker and Anaconda paths, which are not where I'm trying to install extensions.  I had the failure above, uninstalled Docker, deleted Docker paths in Windows Ctrl Panel, deleted Anaconda paths in Windows Ctrl Panel, and got all the same errors as far as I could tell.  I'm not sure where the Docker and Anaconda information are still coming from in yarn-error.log .

**Comment by brettbrocato** [comment]
I have npm installed several jupyter lab build dependencies now, but it looks like I might have to [suspend strict SSL](https://stackoverflow.com/questions/36494336/npm-install-error-unable-to-get-local-issuer-certificate) to get around this:

[excerpt of yarn-error.log]
Trace: 
  Error: unable to get local issuer certificate
      at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
      at emitNone (events.js:106:13)
      at TLSSocket.emit (events.js:208:7)
      at TLSSocket._finishInit (_tls_wrap.js:643:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)
